package theoldone822.ArmorDamageRecalc;

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.apache.commons.lang3.ArrayUtils;

import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemStack;
//import net.minecraft.util.RegistryNamespaced;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.oredict.ShapedOreRecipe;
import net.minecraftforge.oredict.ShapelessOreRecipe;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod(modid = "ArmorDamageRecalc", name = "Armor Damage Recalc", version = "1.1")
public class ArmorDamageRecalc {

	Configuration settings;

	public static boolean trueVanilla = true;

	@Instance("ArmorDamageRecalc")
	public static ArmorDamageRecalc instance = new ArmorDamageRecalc();

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new EventHandlers());
		ModMetadata metadata = event.getModMetadata();
		metadata.autogenerated = false;

		metadata.authorList = Arrays.asList("theoldone822");
		metadata.description = ".";
		File installDir = event.getModConfigurationDirectory();
		File configDir = new File(installDir, "ArmorDamageRecalc");
		settings = new Configuration(new File(configDir, "ArmorDamageRecalc.cfg"));

		settings.load();
		trueVanilla = settings.getBoolean("TrueVanilla", "settings", true, "If true faithfully fallows how vanilla reads armor value thus dropping any values right of the decimal. If false will use exact armor value. Default true");
		settings.save();
	}

}
